### ISSUE TITLE
Can't fix it Unable to load DLL 'tdjson.dll' or one of its dependencies

### ISSUE THREAD

**Issue by Primus-max** [egramtel/tdsharp#165]
### Discussed in https://github.com/egramtel/tdsharp/discussions/164

<div type='discussions-op-text'>

<sup>Originally posted by **Primus-max** March 23, 2023</sup>
In the development environment, everything was fine, the project worked. It's time to transfer to the server, got the following error:
unhandled exception. System.DllNotFoundException: Unable to load DLL 'tdjson.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
    at TdLib.Bindings.WindowsBindings.td_json_client_create()
    at TdLib.Bindings.WindowsBindings.ClientCreate()
    at TdLib.TdJsonClient..ctor(ITdLibBindings bindings)
    at TdLib.TdClient..ctor(ITdLibBindings bindings)
    at TdLib.TdClient..ctor()
    at GetPostsFromTG.TGClient..ctor() in Z:\Programming\ProjectC#\GetPostsFromTG\TGClient.cs:line 27
    at Program.<Main>$(String[] args) in Z:\Programming\ProjectC#\GetPostsFromTG\Program.cs:line 24
    at Program.<Main>(String[] args)
I'm new to programming and can't figure this out on my own. I would really appreciate help.</div>

**Comment by ForNeVeR** [comment]
For now, let's keep the discussion in #164. I don't currently believe this is a _bug_ in tdsharp. More of a build/publication issue of your particular application (I would, of course, be happy to help with advice on that as well).
