### ISSUE TITLE
Unable to load shared library 'libtdjson.dylib'

### ISSUE THREAD

**Issue by fafrd** [egramtel/tdsharp#181]
On MacOS 14.0 (Sonoma), I'm seeing this error:

```bash
~/Documents/telegram % dotnet run
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'libtdjson.dylib' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibtdjson.dylib, 0x0001): tried: 'liblibtdjson.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSliblibtdjson.dylib' (no such file), '/usr/lib/liblibtdjson.dylib' (no such file, not in dyld cache), 'liblibtdjson.dylib' (no such file), '/usr/local/lib/liblibtdjson.dylib' (no such file), '/usr/lib/liblibtdjson.dylib' (no such file, not in dyld cache)
   at TdLib.Bindings.MacosBindings.td_json_client_create()
   at TdLib.Bindings.MacosBindings.ClientCreate()
   at TdLib.TdJsonClient..ctor(ITdLibBindings bindings)
   at TdLib.TdJsonClient..ctor()
   at Program.<Main>$(String[] args) in /Users/kian/Documents/telegram/Program.cs:line 6
```

This is after running `dotnet add package TDLib` and running the basic sample code in the readme. Has anyone else encountered this problem?

**Comment by ForNeVeR** [comment]
Please see the [Dependencies](https://github.com/egramtel/tdsharp#dependencies) section of the README: you are supposed to either provide your own version of tdlib, or use tdlib.native with prepackaged binaries for several platforms.

(Notably, M1 Mac is still absent and is tracked at https://github.com/ForNeVeR/tdlib.native/issues/74.)
