### ISSUE TITLE
InvalidCastException: Unable to cast object of type 'ChatPhoto' to type 'ChatPhotoInfo'.

### ISSUE THREAD

**Issue by majidbigdeli** [egramtel/tdsharp#59]
Newtonsoft.Json.JsonSerializationException
  HResult=0x80131500
  Message=Error setting value to 'Photo' on 'TdLib.TdApi+Chat'.
  Source=Newtonsoft.Json
  StackTrace:
   at Newtonsoft.Json.Serialization.ExpressionValueProvider.SetValue(Object target, Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at TdLib.Converter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in C:\Users\majid\Desktop\tdsharp\TDLib.Api\Converter.cs:line 50
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)

Inner Exception 1:
InvalidCastException: Unable to cast object of type 'ChatPhoto' to type 'ChatPhotoInfo'.

**Comment by shpendpalushi** [comment]
I am having the same problem, did you find any way around it?

**Comment by x2bool** [comment]
I need more info. What method did you call? What is the version of tdsharp? Did you compile tdlib yourself or used TDLib.Native?

**Comment by majidbigdeli** [comment]
I use tdlib.native and i call getchat method  and i use tdsharp last version 1.7

**Comment by x2bool** [comment]
That is the problem. TDLib.Native is 1.6 now. The workaround is to compile tdlib yourself. Or (probably) better option is to help @ForNeVeR with 1.7 builds of TDLib.Native

**Comment by majidbigdeli** [comment]
@x2bool  thank you

**Comment by bichuga** [comment]
> That is the problem. TDLib.Native is 1.6 now. The workaround is to compile tdlib yourself. Or (probably) better option is to help @ForNeVeR with 1.7 builds of TDLib.Native

I built tdlib myself (both x64 and x86), dropped it in the output directory, and I'm still getting the same error. Any idea what I might be doing wrong?

![image](https://user-images.githubusercontent.com/9372553/113742876-e92aa600-96b7-11eb-83ce-0ce67513b08a.png)

**Comment by x2bool** [comment]
@bichuga Do you have exactly the same exception? I mean with ChatPhoto and ChatPhotoInfo? Folks at Telegram sometimes do minor API updates which could break APIs. In that case you could also generate fresh bindings for that particular version and compile it yourself. See: https://github.com/egramtel/tdsharp/issues/62

**Comment by bichuga** [comment]
> @bichuga Do you have exactly the same exception? I mean with ChatPhoto and ChatPhotoInfo? Folks at Telegram sometimes do minor API updates which could break APIs. In that case you could also generate fresh bindings for that particular version and compile it yourself. See: #62

Do you know of a clever way to auto generate the updated object model? I tweaked it by hand and the chats I'm loading are working without throwing now but I'm not convinced I got all the changes

**Comment by x2bool** [comment]
> > @bichuga Do you have exactly the same exception? I mean with ChatPhoto and ChatPhotoInfo? Folks at Telegram sometimes do minor API updates which could break APIs. In that case you could also generate fresh bindings for that particular version and compile it yourself. See: #62
> 
> Do you know of a clever way to auto generate the updated object model? I tweaked it by hand and the chats I'm loading are working without throwing now but I'm not convinced I got all the changes

Yeah. Use https://github.com/egramtel/tdsharp/tree/master/TDLib.CodeGen. Before running update Types.tl and Methods.tl using https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl

**Comment by jrq2** [comment]
> 
> Yeah. Use https://github.com/egramtel/tdsharp/tree/master/TDLib.CodeGen. Before running update Types.tl and Methods.tl using https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl

I must then replace 2 generated folders in TDLIB.API. That's all I need to do? Or do I need to do something else to upgrade to the latest version?
